apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.api.name }}
spec:
  type: {{ .Values.api.service.type }}
  loadBalancerIP: {{ .Values.api.service.externalIP }}
  selector:
    app: {{ .Values.api.name }}
  ports:
    - protocol: TCP
      port: {{ .Values.api.service.port }}
      targetPort: {{ .Values.api.containerPort }}
