apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-db-secret
type: Opaque
stringData:
  DB_PASSWORD: {{ .Values.db.password | quote }}
  DATABASE_URL: "postgresql://{{ .Values.db.user }}:{{ .Values.db.password }}@{{ .Release.Name }}-db-svc:{{ .Values.db.port }}/{{ .Values.db.dbName }}"