apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.db.name }}
spec:
  serviceName: {{ .Values.db.name }}-db-svc
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.db.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.db.name }}
    spec:
      containers:
        - name: postgres
          image: postgres:15
          ports:
            - containerPort: {{ .Values.db.port }}
          env:
            - name: POSTGRES_USER
              value: {{ .Values.db.user | quote }}
            - name: POSTGRES_DB
              value: {{ .Values.db.dbName | quote }}
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-db-secret
                  key: DB_PASSWORD
          volumeMounts:
            - name: pvc-postgres-db
              mountPath: {{ .Values.db.storage.mountpath }}
          resources:
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}

  volumeClaimTemplates:
    - metadata:
        name: pvc-postgres-db
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: {{ .Values.db.storage.size }}