apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-db-svc
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.db.name }}
  ports:
    - protocol: TCP
      port: {{ .Values.db.port }}
      targetPort: {{ .Values.db.port }}