name: Build-push

on:
  workflow_run:
    workflows: ["Tests"]
    branches:
      - main
    types:
      - completed
    

jobs:
  Build-push:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: rkxx/kubetrack
          tags: |
            type=schedule
            type=ref,event=branch
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha
            type=raw,value=latest
         
      - name: Login to DockerHUB
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PAT }}

      - name: Setup docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Build-push docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          
      - name: Upload as artifact
        uses: actions/upload-artifact@v5
        with:
          name: helm-charts
          path: charts/

  Deploy:
    runs-on: self-hosted
    needs: [ Build-push ]
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v5
        with:
          name: helm-charts
          path: ./charts

      - name: Deploy to k3s 
        run: |
          export KUBECONFIG=/etc/rancher/k3s/k3s.yaml
          helm upgrade --install inventory-core ./charts/Kubetrack-inventory-api \
            --namespace default \
            --set image.repository=${{ vars.DOCKERHUB_USERNAME }}/kubetrack \
            --set image.tag=sha-${{ needs.Build-push.outputs.image_tag }} \
            --wait
          
          
          
          
